### ISSUE TITLE
你好 请问这个efi工作的怎么样？

### ISSUE THREAD

**Issue by cnjn** [linruier/-Code01-4800h-hackintosh#1]
我看到另一个人的efi有如下问题
![Screenshot_2023-12-16-03-08-32-594_mark via](https://github.com/linruier/-Code01-4800h-hackintosh/assets/30923815/543af848-d0c4-4bc1-830a-e71b25baaaed)

请问你的efi有解决这些问题的办法吗

**Comment by linruier** [comment]
你好，我这个efi是用的机械革命s1pro的efi，直接用在code01本上（4800h)，实测wifi蓝牙正常，键盘背光，音量，亮度控制等都正常。唯二的缺陷是睡眠有问题和偶尔重启，其它没什么问题，非常好用。建议尝试。
